// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: idl/seekmall/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleCallBackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   []byte                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleCallBackRequest) Reset() {
	*x = HandleCallBackRequest{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleCallBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCallBackRequest) ProtoMessage() {}

func (x *HandleCallBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCallBackRequest.ProtoReflect.Descriptor instead.
func (*HandleCallBackRequest) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{0}
}

func (x *HandleCallBackRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type HandleCallBackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleCallBackResponse) Reset() {
	*x = HandleCallBackResponse{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleCallBackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCallBackResponse) ProtoMessage() {}

func (x *HandleCallBackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCallBackResponse.ProtoReflect.Descriptor instead.
func (*HandleCallBackResponse) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{1}
}

type PrePayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	BizTradeNo    string                 `protobuf:"bytes,5,opt,name=biz_trade_no,json=bizTradeNo,proto3" json:"biz_trade_no,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,6,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePayRequest) Reset() {
	*x = PrePayRequest{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePayRequest) ProtoMessage() {}

func (x *PrePayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePayRequest.ProtoReflect.Descriptor instead.
func (*PrePayRequest) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PrePayRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PrePayRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PrePayRequest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PrePayRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PrePayRequest) GetBizTradeNo() string {
	if x != nil {
		return x.BizTradeNo
	}
	return ""
}

func (x *PrePayRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

type PrePayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeUrl       string                 `protobuf:"bytes,1,opt,name=code_url,json=codeUrl,proto3" json:"code_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePayResponse) Reset() {
	*x = PrePayResponse{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePayResponse) ProtoMessage() {}

func (x *PrePayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePayResponse.ProtoReflect.Descriptor instead.
func (*PrePayResponse) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PrePayResponse) GetCodeUrl() string {
	if x != nil {
		return x.CodeUrl
	}
	return ""
}

type FindExpirePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Time          int64                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindExpirePaymentRequest) Reset() {
	*x = FindExpirePaymentRequest{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindExpirePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindExpirePaymentRequest) ProtoMessage() {}

func (x *FindExpirePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindExpirePaymentRequest.ProtoReflect.Descriptor instead.
func (*FindExpirePaymentRequest) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{4}
}

func (x *FindExpirePaymentRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FindExpirePaymentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindExpirePaymentRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizTradeNo    string                 `protobuf:"bytes,1,opt,name=biz_trade_no,json=bizTradeNo,proto3" json:"biz_trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{5}
}

func (x *Payment) GetBizTradeNo() string {
	if x != nil {
		return x.BizTradeNo
	}
	return ""
}

type FindExpirePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindExpirePaymentResponse) Reset() {
	*x = FindExpirePaymentResponse{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindExpirePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindExpirePaymentResponse) ProtoMessage() {}

func (x *FindExpirePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindExpirePaymentResponse.ProtoReflect.Descriptor instead.
func (*FindExpirePaymentResponse) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{6}
}

func (x *FindExpirePaymentResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type SyncWechatInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizTradeNo    []string               `protobuf:"bytes,1,rep,name=biz_trade_no,json=bizTradeNo,proto3" json:"biz_trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWechatInfoRequest) Reset() {
	*x = SyncWechatInfoRequest{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWechatInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWechatInfoRequest) ProtoMessage() {}

func (x *SyncWechatInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWechatInfoRequest.ProtoReflect.Descriptor instead.
func (*SyncWechatInfoRequest) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{7}
}

func (x *SyncWechatInfoRequest) GetBizTradeNo() []string {
	if x != nil {
		return x.BizTradeNo
	}
	return nil
}

type SyncWechatInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWechatInfoResponse) Reset() {
	*x = SyncWechatInfoResponse{}
	mi := &file_idl_seekmall_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWechatInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWechatInfoResponse) ProtoMessage() {}

func (x *SyncWechatInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_seekmall_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWechatInfoResponse.ProtoReflect.Descriptor instead.
func (*SyncWechatInfoResponse) Descriptor() ([]byte, []int) {
	return file_idl_seekmall_payment_proto_rawDescGZIP(), []int{8}
}

var File_idl_seekmall_payment_proto protoreflect.FileDescriptor

var file_idl_seekmall_payment_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x64, 0x6c, 0x2f, 0x73, 0x65, 0x65, 0x6b, 0x6d, 0x61, 0x6c, 0x6c, 0x2f, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x39, 0x0a, 0x15, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43,
	0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x18, 0x0a, 0x16, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x0d, 0x50,
	0x72, 0x65, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x69, 0x7a, 0x5f, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62,
	0x69, 0x7a, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x50,
	0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f,
	0x64, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x64, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x5c, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20,
	0x0a, 0x0c, 0x62, 0x69, 0x7a, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x7a, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f,
	0x22, 0x49, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x08, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x08, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x39, 0x0a, 0x15, 0x53,
	0x79, 0x6e, 0x63, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x69, 0x7a, 0x5f, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x7a, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x79, 0x6e, 0x63, 0x57, 0x65,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xcd, 0x02, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x50, 0x61, 0x79, 0x12, 0x16, 0x2e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x65, 0x50, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x50, 0x72, 0x65, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51,
	0x0a, 0x0e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b,
	0x12, 0x1e, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5a, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a,
	0x0e, 0x53, 0x79, 0x6e, 0x63, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1e, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x57, 0x65,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x57, 0x65,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_seekmall_payment_proto_rawDescOnce sync.Once
	file_idl_seekmall_payment_proto_rawDescData = file_idl_seekmall_payment_proto_rawDesc
)

func file_idl_seekmall_payment_proto_rawDescGZIP() []byte {
	file_idl_seekmall_payment_proto_rawDescOnce.Do(func() {
		file_idl_seekmall_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_seekmall_payment_proto_rawDescData)
	})
	return file_idl_seekmall_payment_proto_rawDescData
}

var file_idl_seekmall_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_idl_seekmall_payment_proto_goTypes = []any{
	(*HandleCallBackRequest)(nil),     // 0: payment.HandleCallBackRequest
	(*HandleCallBackResponse)(nil),    // 1: payment.HandleCallBackResponse
	(*PrePayRequest)(nil),             // 2: payment.PrePayRequest
	(*PrePayResponse)(nil),            // 3: payment.PrePayResponse
	(*FindExpirePaymentRequest)(nil),  // 4: payment.FindExpirePaymentRequest
	(*Payment)(nil),                   // 5: payment.Payment
	(*FindExpirePaymentResponse)(nil), // 6: payment.FindExpirePaymentResponse
	(*SyncWechatInfoRequest)(nil),     // 7: payment.SyncWechatInfoRequest
	(*SyncWechatInfoResponse)(nil),    // 8: payment.SyncWechatInfoResponse
}
var file_idl_seekmall_payment_proto_depIdxs = []int32{
	5, // 0: payment.FindExpirePaymentResponse.payments:type_name -> payment.Payment
	2, // 1: payment.PaymentService.PrePay:input_type -> payment.PrePayRequest
	0, // 2: payment.PaymentService.HandleCallBack:input_type -> payment.HandleCallBackRequest
	4, // 3: payment.PaymentService.FindExpirePayment:input_type -> payment.FindExpirePaymentRequest
	7, // 4: payment.PaymentService.SyncWechatInfo:input_type -> payment.SyncWechatInfoRequest
	3, // 5: payment.PaymentService.PrePay:output_type -> payment.PrePayResponse
	1, // 6: payment.PaymentService.HandleCallBack:output_type -> payment.HandleCallBackResponse
	6, // 7: payment.PaymentService.FindExpirePayment:output_type -> payment.FindExpirePaymentResponse
	8, // 8: payment.PaymentService.SyncWechatInfo:output_type -> payment.SyncWechatInfoResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_seekmall_payment_proto_init() }
func file_idl_seekmall_payment_proto_init() {
	if File_idl_seekmall_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_seekmall_payment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_seekmall_payment_proto_goTypes,
		DependencyIndexes: file_idl_seekmall_payment_proto_depIdxs,
		MessageInfos:      file_idl_seekmall_payment_proto_msgTypes,
	}.Build()
	File_idl_seekmall_payment_proto = out.File
	file_idl_seekmall_payment_proto_rawDesc = nil
	file_idl_seekmall_payment_proto_goTypes = nil
	file_idl_seekmall_payment_proto_depIdxs = nil
}
