// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ms

import (
	"github.com/crazyfrankie/seekmall/app/ms/repository"
	"github.com/crazyfrankie/seekmall/app/ms/repository/cache"
	"github.com/crazyfrankie/seekmall/app/ms/service"
	"github.com/crazyfrankie/seekmall/app/ms/service/sms/memory"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitModule(cmd redis.Cmdable) *Module {
	smsCache := cache.NewSmsCache(cmd)
	smsRepo := repository.NewSmsRepo(smsCache)
	smsService := memory.NewMemorySms()
	smsSvc := service.NewSmsService(smsRepo, smsService)
	module := &Module{
		Sms: smsSvc,
	}
	return module
}
