// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/seekmall/app/ms"
	"github.com/crazyfrankie/seekmall/app/product"
	"github.com/crazyfrankie/seekmall/app/user"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	v := InitMws()
	db := InitDB()
	cmdable := InitCache()
	module := ms.InitModule(cmdable)
	userModule := user.InitModule(db, module)
	userHandler := userModule.Hdl
	productModule := product.InitModule(db)
	productHandler := productModule.Hdl
	engine := InitWeb(v, userHandler, productHandler)
	app := &App{
		Server: engine,
	}
	return app
}

// wire.go:

type App struct {
	Server *gin.Engine
}

var BaseSet = wire.NewSet(InitDB, InitCache)
