// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/seekmall/app/api/handler"
	"github.com/crazyfrankie/seekmall/app/api/pkg/mws"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitGin() *gin.Engine {
	v := InitMws()
	userServiceClient := InitUserClient()
	smsServiceClient := InitSmsClient()
	userHandler := handler.NewUserHandler(userServiceClient, smsServiceClient)
	productServiceClient := InitProductClient()
	productHandler := handler.NewProductHandler(productServiceClient)
	engine := InitWeb(v, userHandler, productHandler)
	return engine
}

// wire.go:

func InitMws() []gin.HandlerFunc {
	return []gin.HandlerFunc{mws.NewAuthBuilder().
		IgnorePath("/api/user/send-code").
		IgnorePath("/api/user/verify-code").
		Auth(),
	}
}

func InitWeb(mws2 []gin.HandlerFunc, user *handler.UserHandler, product *handler.ProductHandler) *gin.Engine {
	server := gin.Default()
	server.Use(mws2...)

	user.RegisterRoute(server)
	product.RegisterRoute(server)

	return server
}
