// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"github.com/crazyfrankie/seekmall/app/product/handler"
	"github.com/crazyfrankie/seekmall/app/product/repository"
	"github.com/crazyfrankie/seekmall/app/product/repository/dao"
	"github.com/crazyfrankie/seekmall/app/product/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB) *Module {
	sellerDao := dao.NewSellerDao(db)
	purchaserDao := dao.NewPurchaserDao(db)
	productRepo := repository.NewProductRepo(sellerDao, purchaserDao)
	productService := service.NewProductService(productRepo)
	productHandler := handler.NewProductHandler(productService)
	module := &Module{
		Hdl: productHandler,
	}
	return module
}
