// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/crazyfrankie/seekmall/app/ms"
	"github.com/crazyfrankie/seekmall/app/user/handler"
	"github.com/crazyfrankie/seekmall/app/user/repository"
	"github.com/crazyfrankie/seekmall/app/user/repository/dao"
	"github.com/crazyfrankie/seekmall/app/user/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, sms *ms.Module) *Module {
	userDao := dao.NewUserDao(db)
	userRepo := repository.NewUserRepo(userDao)
	userSvc := service.NewUserService(userRepo)
	smsSvc := sms.Sms
	userHandler := handler.NewUserHandler(userSvc, smsSvc)
	module := &Module{
		Hdl: userHandler,
	}
	return module
}
