// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"fmt"
	"github.com/crazyfrankie/seekmall/app/user/biz/repository"
	"github.com/crazyfrankie/seekmall/app/user/biz/repository/dao"
	"github.com/crazyfrankie/seekmall/app/user/biz/rpc"
	"github.com/crazyfrankie/seekmall/app/user/biz/service"
	"github.com/crazyfrankie/seekmall/app/user/config"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"os"
)

// Injectors from wire.go:

func InitApp() *App {
	db := InitDB()
	userDao := dao.NewUserDao(db)
	userRepo := repository.NewUserRepo(userDao)
	smsServiceClient := rpc.InitSmsClient()
	userServer := service.NewUserServer(userRepo, smsServiceClient)
	server := rpc.NewServer(userServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

func InitDB() *gorm.DB {
	dsn := fmt.Sprintf(config.GetConf().MySQL.DSN, os.Getenv("MYSQL_USER"), os.Getenv("MYSQL_PASSWORD"), os.Getenv("MYSQL_HOST"), os.Getenv("MYSQL_PORT"), os.Getenv("MYSQL_DB"))

	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
		NamingStrategy: &schema.NamingStrategy{
			SingularTable: true,
		},
	})
	if err != nil {
		panic(err)
	}

	db.AutoMigrate(&dao.User{})

	return db
}

type App struct {
	server *rpc.Server
}
